$(".moon").click(function(){
    $(".moon").toggleClass("change_color_moon")
    $("body").toggleClass("body")
    $(".portfolio").toggleClass("portfolio_color")
    $(".total_visited").toggleClass("total_visited_color")
    $(".img1").toggleClass("img1_show")
    $(".img2").toggleClass("img2_show")
    $(".box").toggleClass("box_before")
    $(".box").toggleClass("box_highlight")
    $(".my_cv").toggleClass("my_cv_highlight")
    $(".github").toggleClass("github_highlight")
    $(".footer_section").toggleClass("footer_section_highlight")
    $(".digital-clock").toggleClass("digital-clock_highlight")
    $(".show-more-btn").toggleClass("show-more-btn_highlight")
    $(".box p").toggleClass("box_p")
    $(".icons").toggleClass("icons_color")
    $(".section_title").toggleClass("section_title_color")
    $(".cursor").toggleClass("cursor_color")
    $(".cursor2").toggleClass("cursor2_color")
    $(".second_section").toggleClass("second_section_color")
    $(".third_section").toggleClass("third_section_color")
    $(".fourth_section").toggleClass("fourth_section_color")
    $(".fifth_section").toggleClass("fifth_section_color")
    $(".sixth_section").toggleClass("sixth_section_color")
    $(".seventh_section").toggleClass("seventh_section_color")
    $(".eight_section").toggleClass("eight_section_color")
    $(".nine_section").toggleClass("nine_section_color")
    $(".tenth_section").toggleClass("tenth_section_color")
    $(".my_cv").toggleClass("tenth_section_color")
    $(".tenth_section input").toggleClass("contact_input")
    $(".tenth_section textarea").toggleClass("contact_input")
    $(".footer_section span").toggleClass("footer_section_color")
});